[package]
name = "garland"
version = "0.1.0"
authors = ["Christopher Anderson <'chris@nullcode.org'>"]
edition = "2018"

[dependencies]
http = "0.1.13"
url = "1.7.1"
reqwest = "0.9.3"
log = "0.4.5"
serde_json = "1.0.32"
failure = "0.1.2"
serde_derive = "1.0.80"
serde = "1.0.80"
