[package]
name = "xivapi"
version = "0.1.0"
authors = ["Christopher Anderson <'chris@nullcode.org'>"]
edition = "2018"

[dependencies]
url = "2.1.1"
log = "0.4.8"
serde_json = "1.0.46"
serde = { version = "1.0.104", features = ["derive"] }
ureq = "0.11.3"
anyhow = "1.0.26"
