name: Rust

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
        with:
            toolchain: nightly
    - name: Run tests
      run: cargo test --verbose
        with:
            toolchain: nightly
